spring:
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/historymap
    username: postgres
    password: password
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/webapp/,classpath:/public/,file:/home/brin/Dev/random/pictureStore




logging:
  level:
      org.springframework.web: INFO
      org.hibernate: ERROR
      wien.historymap: DEBUG


google.apikey: AIzaSyBYV-WN6EWN4EBpHdq-5tr1x-mfpvFzPy4