spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/culherviz
    username: postgres
    password: password
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/webapp/,classpath:/public/,file:D:/Dev/workspaces/culherviz/pictureStore


logging:
  level:
      org.springframework.web: INFO
      org.hibernate: ERROR
      wien.historymap: DEBUG


google.apikey: AIzaSyBYV-WN6EWN4EBpHdq-5tr1x-mfpvFzPy4